### ISSUE TITLE
Experiment code for PX4 flight program

### ISSUE THREAD

**Issue by wangwwno1** [DependableSystemsLab/stealthy-attacks#2]
Hello, I'm just read your paper on DTRAP and thanks for sharing the source code of your experiment.

The extended version of this paper has implement attacks on the PX4 platform. Could you release the experiment code on PX4 platform so I can reproduce the attack?

**Comment by dashpritam** [comment]
Hi, Thanks for your interest in this work. The attack code can be found in libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.cpp, and libraries/AP_Motors/AP_MotorsMatrix.cpp files. The code snippet that triggers the attacks is labeled based on the attack type.  

These attacks can be reproduced in PX4 by using the same code in the following files - src/modules/mc_pos_control/PositionControl.cpp, src/modules/mc_pos_control/AttitudeControl.cpp and/or src/modules/dataFusion/referenceMonitor.cpp. Make sure you are calling the attack code in a function related to position or attitude control.
